{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "exam-controller.fullname" . }}-metrics-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "exam-controller.labels" . | nindent 4 }}
spec:
  endpoints:
  - path: /metrics
    port: https
    scheme: https
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    {{- if .Values.metrics.serviceMonitor.interval }}
    interval: {{ .Values.metrics.serviceMonitor.interval }}
    {{- end }}
    tlsConfig:
      insecureSkipVerify: true
  selector:
    matchLabels:
      {{- include "exam-controller.selectorLabels" . | nindent 6 }}
{{- end }}
