{{- if .Values.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "exam-controller.fullname" . }}-validating-webhook-configuration
  labels:
    {{- include "exam-controller.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "exam-controller.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-exam-otu-ca-v1alpha1-exam
  failurePolicy: Fail
  name: vexam-v1alpha1.kb.io
  rules:
  - apiGroups:
    - exam.otu.ca
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - exams
  sideEffects: None
{{- end }}
