---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-exam-otu-ca-v1alpha1-exam
  failurePolicy: Fail
  name: vexam-v1alpha1.kb.io
  rules:
  - apiGroups:
    - exam.otu.ca
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - exams
  sideEffects: None
