---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "exam-controller.fullname" . }}-exam-admin-role
  labels:
    {{- include "exam-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - exam.otu.ca
  resources:
  - exams
  verbs:
  - '*'
- apiGroups:
  - exam.otu.ca
  resources:
  - exams/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "exam-controller.fullname" . }}-exam-editor-role
  labels:
    {{- include "exam-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - exam.otu.ca
  resources:
  - exams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - exam.otu.ca
  resources:
  - exams/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "exam-controller.fullname" . }}-exam-viewer-role
  labels:
    {{- include "exam-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - exam.otu.ca
  resources:
  - exams
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - exam.otu.ca
  resources:
  - exams/status
  verbs:
  - get
