//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DryRunFailure) DeepCopyInto(out *DryRunFailure) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DryRunFailure.
func (in *DryRunFailure) DeepCopy() *DryRunFailure {
	if in == nil {
		return nil
	}
	out := new(DryRunFailure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DryRunStatus) DeepCopyInto(out *DryRunStatus) {
	*out = *in
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Failures != nil {
		in, out := &in.Failures, &out.Failures
		*out = make([]DryRunFailure, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DryRunStatus.
func (in *DryRunStatus) DeepCopy() *DryRunStatus {
	if in == nil {
		return nil
	}
	out := new(DryRunStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Exam) DeepCopyInto(out *Exam) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Exam.
func (in *Exam) DeepCopy() *Exam {
	if in == nil {
		return nil
	}
	out := new(Exam)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Exam) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExamDryRunSpec) DeepCopyInto(out *ExamDryRunSpec) {
	*out = *in
	out.Before = in.Before
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExamDryRunSpec.
func (in *ExamDryRunSpec) DeepCopy() *ExamDryRunSpec {
	if in == nil {
		return nil
	}
	out := new(ExamDryRunSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExamEmail) DeepCopyInto(out *ExamEmail) {
	*out = *in
	out.Before = in.Before
	out.SendInterval = in.SendInterval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExamEmail.
func (in *ExamEmail) DeepCopy() *ExamEmail {
	if in == nil {
		return nil
	}
	out := new(ExamEmail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExamList) DeepCopyInto(out *ExamList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Exam, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExamList.
func (in *ExamList) DeepCopy() *ExamList {
	if in == nil {
		return nil
	}
	out := new(ExamList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExamList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExamSchedule) DeepCopyInto(out *ExamSchedule) {
	*out = *in
	in.Unlock.DeepCopyInto(&out.Unlock)
	out.Duration = in.Duration
	out.ProvisionBefore = in.ProvisionBefore
	out.Retention = in.Retention
	if in.DryRun != nil {
		in, out := &in.DryRun, &out.DryRun
		*out = new(ExamDryRunSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExamSchedule.
func (in *ExamSchedule) DeepCopy() *ExamSchedule {
	if in == nil {
		return nil
	}
	out := new(ExamSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExamSpec) DeepCopyInto(out *ExamSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
	in.Schedule.DeepCopyInto(&out.Schedule)
	if in.Students != nil {
		in, out := &in.Students, &out.Students
		*out = make([]ExamStudent, len(*in))
		copy(*out, *in)
	}
	out.Email = in.Email
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExamSpec.
func (in *ExamSpec) DeepCopy() *ExamSpec {
	if in == nil {
		return nil
	}
	out := new(ExamSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExamStatus) DeepCopyInto(out *ExamStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ComputedLockTime != nil {
		in, out := &in.ComputedLockTime, &out.ComputedLockTime
		*out = (*in).DeepCopy()
	}
	if in.ProvisionTime != nil {
		in, out := &in.ProvisionTime, &out.ProvisionTime
		*out = (*in).DeepCopy()
	}
	if in.EmailTime != nil {
		in, out := &in.EmailTime, &out.EmailTime
		*out = (*in).DeepCopy()
	}
	if in.RetentionDeadline != nil {
		in, out := &in.RetentionDeadline, &out.RetentionDeadline
		*out = (*in).DeepCopy()
	}
	if in.DryRun != nil {
		in, out := &in.DryRun, &out.DryRun
		*out = new(DryRunStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Students != nil {
		in, out := &in.Students, &out.Students
		*out = make([]StudentStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Spares != nil {
		in, out := &in.Spares, &out.Spares
		*out = make([]SpareStatus, len(*in))
		copy(*out, *in)
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(MetricsSummary)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExamStatus.
func (in *ExamStatus) DeepCopy() *ExamStatus {
	if in == nil {
		return nil
	}
	out := new(ExamStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExamStudent) DeepCopyInto(out *ExamStudent) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExamStudent.
func (in *ExamStudent) DeepCopy() *ExamStudent {
	if in == nil {
		return nil
	}
	out := new(ExamStudent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExamTemplate) DeepCopyInto(out *ExamTemplate) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExamTemplate.
func (in *ExamTemplate) DeepCopy() *ExamTemplate {
	if in == nil {
		return nil
	}
	out := new(ExamTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsSummary) DeepCopyInto(out *MetricsSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsSummary.
func (in *MetricsSummary) DeepCopy() *MetricsSummary {
	if in == nil {
		return nil
	}
	out := new(MetricsSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpareStatus) DeepCopyInto(out *SpareStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpareStatus.
func (in *SpareStatus) DeepCopy() *SpareStatus {
	if in == nil {
		return nil
	}
	out := new(SpareStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StudentStatus) DeepCopyInto(out *StudentStatus) {
	*out = *in
	if in.EmailSentAt != nil {
		in, out := &in.EmailSentAt, &out.EmailSentAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StudentStatus.
func (in *StudentStatus) DeepCopy() *StudentStatus {
	if in == nil {
		return nil
	}
	out := new(StudentStatus)
	in.DeepCopyInto(out)
	return out
}
